name: 'Send message to Telegram'
description: 'Action for send message in Telegram'
inputs:
  token:
    description: "Token bot"
    required: true
  text:
    description: 'The message that will be sent to telegram.'
    required: true
  chat_id:
    description: 'Chat id to relay message'
    required: false
    default: '-324719594'
runs:
  using: "docker"
  image: "Dockerfile"
