name: 'Send message to Telegram'
inputs:
  token:
    description: "Token bot"
    required: true
  text:
    description: 'The message that will be sent to telegram.'
    required: true
description: 'Action for send message in Telegram'
runs:
  using: 'composite'
  steps:
    - run: python $GITHUB_ACTION_PATH/send_message.py
      env:
        TG_TOKEN: ${{ inputs.token }}
        CHAT_ID: -324719594
        TEXT: ${{ inputs.text }}
      shell: bash
