name: Telegram Bridge

# triggers for notifying
# these are some important trigger cases could be change as need
# check here https://developer.github.com/webhooks/
on:
  issue_comment:
    types: [ created ]
  issues:
    types: [ opened, edited, closed, reopened ]
  pull_request:
    types: [ opened, ready_for_review, review_requested, reopened ]
  pull_request_review_comment:
    types: [ created ]
  push:

jobs:
  build:
    name: Telegram Bridge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify about issue comment
        if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created'}}
        uses: ./.github/actions/tg
        with:
          text: "🗣 Комментарий от @${{ github.event.comment.user.login }} в [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) - ${{ github.event.comment.body }}"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about new issue
        if: ${{ github.event_name == 'issues' && github.event.action == 'opened'}}
        uses: ./.github/actions/tg
        with:
          text: "👾 Задач привалило: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) от @${{ github.event.issue.user.login }}"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about edit issue
        if: ${{ github.event_name == 'issues' && github.event.action == 'edited'}}
        uses: ./.github/actions/tg
        with:
          text: "🗒 Обновлена задача: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about issue closed
        if: ${{ github.event_name == 'issues' && github.event.action == 'closed'}}
        uses: ./.github/actions/tg
        with:
          text: "🏁 Грац! Закрыта задача: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about issue reopen
        if: ${{ github.event_name == 'issues' && github.event.action == 'reopened'}}
        uses: ./.github/actions/tg
        with:
          text: "♻️ Что-то не доделали в задаче, снова открыта: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about PR open
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened'}}
        uses: ./.github/actions/tg
        with:
          text: "🛠 @${{ github.event.pull_request.user.login}} хочет влить [${{ github.event.pull_request.title}}](${{ github.event.pull_request.html_url}})"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about push in master
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master'}}
        uses: ./.github/actions/tg
        with:
          text: "💚 Новый пуш ${{ github.event.head_commit.message}} в мастере от @${{ github.event.head_commit.author.username}}"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about push
        if: always()
        uses: hmarr/debug-action@v1.0.0
