name: Telegram Bridge

# triggers for notifying
# these are some important trigger cases could be change as need
# check here https://developer.github.com/webhooks/
on:
  issue_comment:
    types: [ created ]
  issues:
    types: [ opened, edited, pinned, closed, reopened, assigned, labeled ]
  pull_request:
    types: [ opened, closed, edited, ready_for_review, review_requested, reopened ]
  pull_request_review_comment:
    types: [ created ]
  push:

jobs:
  build:
    name: Telegram Bridge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify about issue comment
        if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created'}}
        uses: ./.github/actions/tg
        with:
          text: "🗣 Комментарий от @${{ github.event.comment.user.login }} в [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) - ${{ github.event.comment.body }}"
          token: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
      - name: Notify about push
        if: always()
        uses: hmarr/debug-action@v1.0.0
